# Generated by Django 2.2.8 on 2020-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_genre',
        ),
        migrations.AddField(
            model_name='profile',
            name='shopkeeper',
            field=models.BooleanField(default=False),
        ),
    ]
