# Generated by Django 2.2.1 on 2020-06-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Bengaluru', 'Bengaluru'), ('Chennai', 'Chennai'), ('Chittorgarh', 'Chittorgarh'), ('Jodhpur', 'Jodhpur'), ('Raipur', 'Raipur'), ('Sirohi', 'Sirohi'), ('Pali', 'Pali'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Kanpur', 'Kanpur'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Ratnagiri', 'Ratnagiri'), ('Pune', 'Pune'), ('Surat', 'Surat'), ('Sultanpur', 'Sultanpur'), ('Lucknow', 'Lucknow'), ('Patna', 'Patna'), ('Indore', 'Indore'), ('Vadodara', 'Vadodara'), ('Bhopal', 'Bhopal'), ('Coimbatore', 'Coimbatore'), ('Agra', 'Agra'), ('Meerut', 'Meerut'), ('Madurai', 'Madurai'), ('Guwahati', 'Guwahati'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Tiruchchirappalli', 'Tiruchchirappalli'), ('Kota', 'Kota'), ('Jammu', 'Jammu'), ('Mangalore', 'Mangalore'), ('Ajmer', 'Ajmer'), ('Shillong', 'Shillong'), ('New Delhi', 'New Delhi')], max_length=100, null=True)),
                ('zone', models.CharField(choices=[('RED ZONE', 'R'), ('ORANGE ZONE', 'O'), ('GREEN ZONE', 'G')], max_length=30, null=True)),
                ('loc_x', models.DecimalField(decimal_places=6, max_digits=10)),
                ('loc_y', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('locname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
