# Generated by Django 2.2.8 on 2020-06-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='time_slot',
            field=models.CharField(choices=[('Morning Slot', 'Morning  {8 am - 12 pm}'), ('Noon Slot', 'Noon {12 pm - 7 pm}'), ('Night Slot', 'Night {7 pm - 11 pm}')], default='Noon {12 pm - 7 pm}', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(choices=[('Bhim Colony', 'Bhim Colony'), ('Basai Enclave-2', 'Basai Enclave-2'), ('Chandan Vihar', 'Chandan Vihar'), ('Ganga Vihar', 'Ganga Vihar'), ('Sai Kunj', 'Sai Kunj'), ('Shri Ram Colony', 'Shri Ram Colony'), ('Amanpura Colony', 'Amanpura Colony'), ('Patel Nagar Ext', 'Patel Nagar Ext'), ('Shiv Nagar', 'Shiv Nagar'), ('Vikas Nagar', 'Vikas Nagar'), ('Basai Enclave Ext', 'Basai Enclave Ext'), ('Krishna Nagar', 'Krishna Nagar'), ('Surya Vihar', 'Surya Vihar'), ('Ashok Vihar', 'Ashok Vihar'), ('Rajeev colony', 'Rajeev colony'), ('Nihal Vihar', 'Nihal Vihar'), ('Mayur Kunj', 'Mayur Kunj'), ('Ryan Enclave', 'Ryan Enclave'), ('Shyam Kunj', 'Shyam Kunj'), ('Shanti Kunj', 'Shanti Kunj'), ('Mohan Nagar', 'Mohan Nagar'), ('Vatika Kunj', 'Vatika Kunj'), ('Defense Enclave', 'Defense Enclave')], max_length=100, null=True),
        ),
    ]
