# Generated by Django 2.2.8 on 2020-06-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200628_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='locality',
        ),
    ]
