# Generated by Django 2.2.8 on 2020-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200628_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
